/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IscrizioneImpresaRouteImport } from './routes/iscrizione-impresa'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiNotifyStatoRouteImport } from './routes/api/notify-stato'
import { Route as AziendeSlugRouteImport } from './routes/aziende.$slug'
import { Route as AziendeSlugAdminRouteImport } from './routes/aziende.$slug.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IscrizioneImpresaRoute = IscrizioneImpresaRouteImport.update({
  id: '/iscrizione-impresa',
  path: '/iscrizione-impresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyStatoRoute = ApiNotifyStatoRouteImport.update({
  id: '/api/notify-stato',
  path: '/api/notify-stato',
  getParentRoute: () => rootRouteImport,
} as any)
const AziendeSlugRoute = AziendeSlugRouteImport.update({
  id: '/aziende/$slug',
  path: '/aziende/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AziendeSlugAdminRoute = AziendeSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AziendeSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iscrizione-impresa': typeof IscrizioneImpresaRoute
  '/profilo': typeof ProfiloRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/notify-stato': typeof ApiNotifyStatoRoute
  '/aziende/$slug': typeof AziendeSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/aziende/$slug/admin': typeof AziendeSlugAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iscrizione-impresa': typeof IscrizioneImpresaRoute
  '/profilo': typeof ProfiloRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/notify-stato': typeof ApiNotifyStatoRoute
  '/aziende/$slug': typeof AziendeSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/aziende/$slug/admin': typeof AziendeSlugAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iscrizione-impresa': typeof IscrizioneImpresaRoute
  '/profilo': typeof ProfiloRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/notify-stato': typeof ApiNotifyStatoRoute
  '/aziende/$slug': typeof AziendeSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/aziende/$slug/admin': typeof AziendeSlugAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iscrizione-impresa'
    | '/profilo'
    | '/sitemap.xml'
    | '/admin/login'
    | '/api/notify-stato'
    | '/aziende/$slug'
    | '/admin/'
    | '/aziende/$slug/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iscrizione-impresa'
    | '/profilo'
    | '/sitemap.xml'
    | '/admin/login'
    | '/api/notify-stato'
    | '/aziende/$slug'
    | '/admin'
    | '/aziende/$slug/admin'
  id:
    | '__root__'
    | '/'
    | '/iscrizione-impresa'
    | '/profilo'
    | '/sitemap.xml'
    | '/admin/login'
    | '/api/notify-stato'
    | '/aziende/$slug'
    | '/admin/'
    | '/aziende/$slug/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IscrizioneImpresaRoute: typeof IscrizioneImpresaRoute
  ProfiloRoute: typeof ProfiloRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiNotifyStatoRoute: typeof ApiNotifyStatoRoute
  AziendeSlugRoute: typeof AziendeSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iscrizione-impresa': {
      id: '/iscrizione-impresa'
      path: '/iscrizione-impresa'
      fullPath: '/iscrizione-impresa'
      preLoaderRoute: typeof IscrizioneImpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-stato': {
      id: '/api/notify-stato'
      path: '/api/notify-stato'
      fullPath: '/api/notify-stato'
      preLoaderRoute: typeof ApiNotifyStatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aziende/$slug': {
      id: '/aziende/$slug'
      path: '/aziende/$slug'
      fullPath: '/aziende/$slug'
      preLoaderRoute: typeof AziendeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aziende/$slug/admin': {
      id: '/aziende/$slug/admin'
      path: '/admin'
      fullPath: '/aziende/$slug/admin'
      preLoaderRoute: typeof AziendeSlugAdminRouteImport
      parentRoute: typeof AziendeSlugRoute
    }
  }
}

interface AziendeSlugRouteChildren {
  AziendeSlugAdminRoute: typeof AziendeSlugAdminRoute
}

const AziendeSlugRouteChildren: AziendeSlugRouteChildren = {
  AziendeSlugAdminRoute: AziendeSlugAdminRoute,
}

const AziendeSlugRouteWithChildren = AziendeSlugRoute._addFileChildren(
  AziendeSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IscrizioneImpresaRoute: IscrizioneImpresaRoute,
  ProfiloRoute: ProfiloRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiNotifyStatoRoute: ApiNotifyStatoRoute,
  AziendeSlugRoute: AziendeSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
